### ISSUE TITLE
Garbled character

### ISSUE THREAD

**Issue by CwjXFH** [jflbr/jwt-decoder#5]
Hi，
How do I resolve this problem, Thanks!
![image](https://user-images.githubusercontent.com/11468733/92559433-315d2380-f2a3-11ea-9e0d-1e2e353e822f.png)

**Comment by clfsoft** [comment]
https://github.com/jflbr/jwt-decoder/blob/a5e298c433cdc313d38c3d7b70e1d0af4808df11/src/jwt.ts#L5
↑　⇒　return JSON.parse(Buffer.from(base64, 'base64').toString());
you can manually edit the following file under VsCode   
extensions\jflbr.jwt-decoder-1.2.0\out\jwt.js
